### ISSUE TITLE
Failure running `machina-install`

### ISSUE THREAD

**Issue by sebastian** [RefugeesOnRails/machina#3] opened 2015-11-23 07:59 UTC
On a completely fresh install of Ubuntu 14.04.3 LTS I get the following error message when running the machina install script:

```
...

TASK: [install pip] *********************************************************** 
ok: [localhost]

TASK: [install awscli] ******************************************************** 
failed: [localhost] => {"cmd": "/usr/bin/pip install awscli", "failed": true}
msg: stdout: Downloading/unpacking awscli
Downloading/unpacking docutils>=0.10 (from awscli)
  Running setup.py (path:/tmp/pip_build_root/docutils/setup.py) egg_info for package docutils

    warning: no files found matching 'MANIFEST'
    warning: no files found matching '*' under directory 'extras'
    warning: no previously-included files matching '.cvsignore' found under directory '*'
    warning: no previously-included files matching '*.pyc' found under directory '*'
    warning: no previously-included files matching '*~' found under directory '*'
    warning: no previously-included files matching '.DS_Store' found under directory '*'
Downloading/unpacking rsa>=3.1.2,<=3.3.0 (from awscli)
Requirement already satisfied (use --upgrade to upgrade): colorama>=0.2.5,<=0.3.3 in /usr/lib/python2.7/dist-packages (from awscli)
Downloading/unpacking botocore==1.3.8 (from awscli)
  Hash of the package https://pypi.python.org/packages/py2.py3/b/botocore/botocore-1.3.8-py2.py3-none-any.whl#md5=023986ffe0ff878a87d5680ddc8fdcce (from https://pypi.python.org/simple/botocore/) (cdb84ef247eb067ba2b6ec6ceb15b45b) doesn't match the expected hash 023986ffe0ff878a87d5680ddc8fdcce!
Cleaning up...
Bad md5 hash for package https://pypi.python.org/packages/py2.py3/b/botocore/botocore-1.3.8-py2.py3-none-any.whl#md5=023986ffe0ff878a87d5680ddc8fdcce (from https://pypi.python.org/simple/botocore/)
Storing debug log for failure in /root/.pip/pip.log


FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/sebastian/site.retry

localhost                  : ok=12   changed=8    unreachable=0    failed=1 
```

For what it is worth, I am running in VirtualBox with guest add-ons installed.

**Comment by sangyye** [comment] 2015-11-23 08:01
Hey, thanks for reporting, can I get the pip.log to see the reason for the pip failure?

**Comment by sebastian** [comment] 2015-11-23 08:06
Sure! But where are they?
I don't normally use pip, so not quite sure where to look. Some googling indicate that they should be under `~/.pip/...` but that folder doesn't exist, nor is there anything under `/var/log/...`.

I did a second run of the script and now it seems to have progressed past the previous failure.

I'll let the setup continue. If the logs are no-longer intact, then I'll restore the machine back to the earlier clean state and re-run it in order to see if I can reproduce the error.

**Comment by sangyye** [comment] 2015-11-23 08:08
Hm, it should be in `/root/.pip/pip.log`, I just reinstall ubuntu in a virtual machine to reproduce the error. Maybe I should change the install method a little bit.

**Comment by sebastian** [comment] 2015-11-23 08:22
You can find my pip-log [here](https://gist.github.com/sebastian/472463fa98142f104f54).
Let me know if there is anything else I can do to help / help test.

**Comment by sangyye** [comment] 2015-11-23 08:25
Thanks, will look into it

**Comment by sangyye** [comment] 2015-11-23 08:27
It seems it is an error with pip and not directly a error in machina script

`HashMismatch: Bad md5 hash for package https://pypi.python.org/packages/py2.py3/b/botocore/botocore-1.3.8-py2.py3-none-any.whl#md5=023986ffe0ff878a87d5680ddc8fdcce (from https://pypi.python.org/simple/botocore/)`

Maybe some error in the download, can you reset and test it again?

**Comment by sangyye** [comment] 2015-11-23 08:58
Okay, I tested it in a fresh ubuntu 14.04, and wasn't able to reproduce the error.

I could install pip via the package repo of ubuntu instead of easy_install. But at the moment it is working fine.

**Comment by sebastian** [comment] 2015-11-23 12:14
Another issue when running again from scratch (sorry this is taking some time, as I have a rather packed day today).

I am now getting:

```
...

Ign http://de.archive.ubuntu.com trusty/main Translation-en_US                 
Ign http://de.archive.ubuntu.com trusty/multiverse Translation-en_US           
Ign http://de.archive.ubuntu.com trusty/restricted Translation-en_US           
Ign http://de.archive.ubuntu.com trusty/universe Translation-en_US             
Fetched 2.461 kB in 45s (54,3 kB/s)                                            
E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem. 
E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem. 
SUDO password: 

PLAY [all] ******************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [get the real username when not ssh] ************************************ 
skipping: [localhost]

TASK: [set USER via id] ******************************************************* 
skipping: [localhost]

TASK: [set USER via ssh] ****************************************************** 
ok: [localhost]

TASK: [update apt cache] ****************************************************** 
ok: [localhost]

TASK: [install packages] ****************************************************** 
ok: [localhost] => (item=aptitude,build-essential,git,postgresql,redis-server,python-dev,python-setuptools,python-virtualenv,python-pycurl,libssl-dev,libreadline-dev,zlib1g-dev,libffi-dev)

TASK: [Upgrade all Packages] ************************************************** 
failed: [localhost] => {"failed": true}
stdout: Reading package lists...
Building dependency tree...
Reading state information...
Reading extended state information...
Initializing package states...

msg: '/usr/bin/aptitude safe-upgrade' failed: E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem. 
W: Could not lock the cache file; this usually means that dpkg or another apt tool is already installing packages.  Opening in read-only mode; any changes you make to the states of packages will NOT be preserved!
E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem. 


FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/sebastian/site.retry

localhost                  : ok=4    changed=0    unreachable=0    failed=1   

sebastian@sebastian-ubuntu:~$ 
```

For reference: I am not doing anything else on this machine. It's a fresh install again and I have just restarted the machine.

I saw this same error yesterday when testing out of the WunderAgents office, but didn't have time to copy it out then.

Will try to re-run the script.

**Comment by sangyye** [comment] 2015-11-23 12:18
Hey,

try to remove the lockfile of apt.`sudo rm /var/lib/dpkg/lock` and then run again, I tested it three times (2x in virtualbox, 1x on real hardware) with a fresh install and it works for me every time. This error happens if you kill the ansible process before it finished the apt commands. But I never saw this error before.

**Comment by sebastian** [comment] 2015-11-23 14:24
Yay, this time around it worked :)

**Comment by sangyye** [comment] 2015-11-23 14:27
Nice, but it should work on a fresh installed ubuntu 14.04 on the first try. If you can vertify that, I will close the issue.

**Comment by sebastian** [comment] 2015-11-23 15:09
This time it worked on a fresh install.
I have about 50% success rate so far.

**Comment by sebastian** [comment] 2015-11-23 15:10
It might very well be associated with my local setup in some form.
Let's close it for now and see.

**Comment by sangyye** [comment] 2015-11-23 15:12
Okay, will close this now.

**Closed as completed by sangyye** 2015-11-23 15:12 UTC
Labels: bug
