### ISSUE TITLE
I get this error on apt-update

### ISSUE THREAD

**Issue by vincvan** [RefugeesOnRails/machina#15] opened 2016-10-28 15:49 UTC
`Reading package lists... Done
W: The repository 'http://ppa.launchpad.net/ansible/ansible/ubuntu yakkety Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://ppa.launchpad.net/ansible/ansible/ubuntu/dists/yakkety/main/binary-i386/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.`

**Comment by sangyye** [comment] 2016-11-10 18:36
- Which Version from Ubuntu are you Running?
- Are you using the 64bit version of Ubuntu?

EDIT: Just test it with two laptops running Ubuntu 14.04 64bit and can't reproduce your problem.

**Comment by sangyye** [comment] 2017-02-01 20:42
I close this because there was no answer, please reopen it if needed.

**Closed as completed by sangyye** 2017-02-01 20:42 UTC
